stages:
  - build

.node:
  image: node:24.13.1
  before_script:
    - npm ci

build:
  extends:
    - .node
  stage: build
  parallel:
    matrix:
      - EDITION:
          - ce
          - ee
          - cloud
  script:
    - '[[ $EDITION == "ce" ]] && rm -rf src/packages/{ee,cloud}'
    - '[[ $EDITION == "ee" ]] && rm -rf src/packages/cloud'
    - npm run build
